version: '3'

services: 
  database:
    image: mongo
    ports:
     - "27017:27017"
  frontend:
    build: frontend/front
    ports:
      - "3000:80"
  backend:
    build: backend/serverapi
    ports:
      - "4000:4000"
    

